export * from './personne-physique.model';
export * from './personne-physique-popup.service';
export * from './personne-physique.service';
export * from './personne-physique-dialog.component';
export * from './personne-physique-dialog-for-detail.component';
export * from './personne-physique-delete-dialog.component';
export * from './personne-physique-detail.component';
export * from './personne-physique.component';
export * from './personne-physique.route';
