package com.gaconnecte.auxilium.drools


import com.gaconnecte.auxilium.drools.FactDevis

rule "Assujettie for  TVA DOMMAGES COLLISIONS" 

 when 
     devisObject: FactDevis(isAssujettie.equals(true)) && FactDevis(modeId == 5) 
 then
 
    Float tva = 0.19F;
    Float vetuse = 0F;
	Float franchise = 0F;
 
/********************** SALIM ******************/

   if(devisObject.getCompagnieId() == 1 || devisObject.getCompagnieId() == 6 || devisObject.getCompagnieId() == 8 
	 || devisObject.getCompagnieId() == 5 || devisObject.getCompagnieId() == 7 || devisObject.getCompagnieId() == 2
	 || devisObject.getCompagnieId() == 4){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
	       devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(Double.valueOf(devisObject.getTva()));
	     
	 // Engagement GA
	 
	  if(Float.valueOf(devisObject.getTotHt().toString()) < Float.valueOf(devisObject.getCapitalRestant().toString())){
	      
	      if(devisObject.getDepassplafondInput() < 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString()) 
				
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    );
				}
				if(devisObject.getDepassplafondInput() >= 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString())
				- devisObject.getDepassplafondInput() 
				
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    );
				}
	    }
			if(Float.valueOf(devisObject.getTotHt().toString()) > Float.valueOf(devisObject.getCapitalRestant().toString())){
	    
	      if(devisObject.getDepassplafondInput() < 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString()) 
				
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    );
				}
				if(devisObject.getDepassplafondInput() >= 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString())
				- devisObject.getDepassplafondInput() 
				
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    );
				}
	    }
	    
	 // End engagemnt GA
	
		  if(devisObject.getDepassplafondInput() < 0){
		    
		    devisObject.setDepassplafond(0F);
		    devisObject.setTotalPartAssuree(Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

				if((Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
				
		    
		    }else{
		    
		    devisObject.setDepassplafond(devisObject.getDepassplafondInput());
		    
		    devisObject.setTotalPartAssuree(devisObject.getDepassplafondInput()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

				if((Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInput() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getDepassplafondInput()
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInput() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    }

	
 }

/********************** LA CARTE ******************/

    if(devisObject.getCompagnieId() == 3){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
	       devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(Double.valueOf(devisObject.getTva()));
	     
	 // Engagement GA
	 
	  if(Float.valueOf(devisObject.getRegleproporAssujettieCarte().toString()) < Float.valueOf(devisObject.getCapitalRestant().toString())){

	      if(Float.valueOf(devisObject.getValeurNeufCarte().toString()) < 50000F){

	      devisObject.setEngagementGa(
					(Float.valueOf(devisObject.getTotHt().toString()) 
	      -
				 Float.valueOf(devisObject.getVetuste().toString()))
				*
                                 Float.valueOf(devisObject.getRpDV().toString())
	      -
				 Float.valueOf(devisObject.getFranchiseInput().toString()));

				}
				if(Float.valueOf(devisObject.getValeurNeufCarte().toString()) >= 50000F){


	      if(devisObject.getDepassplafondInput() < 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString()) 
				
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    );
				}
				if(devisObject.getDepassplafondInput() >= 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString())
				- devisObject.getDepassplafondInput() 
				
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    );
				}

				}

	    }
			if(Float.valueOf(devisObject.getRegleproporAssujettieCarte().toString()) >= Float.valueOf(devisObject.getCapitalRestant().toString()))
			{
	    
	      if(devisObject.getDepassplafondInput() < 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString()) 
				
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    );
				}
				if(devisObject.getDepassplafondInput() >= 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString())
				- devisObject.getDepassplafondInput() 
				
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    );
				}
			}
		devisObject.setReglepropor(devisObject.getRegleproporAssujettie());
	    
	 // End engagemnt GA
	
		  if(devisObject.getDepassplafondInput() < 0){
		    
		    devisObject.setDepassplafond(0F);
		    devisObject.setTotalPartAssuree(Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
				+ devisObject.getRegleproporAssujettie()
		    );

        if((Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())
				- devisObject.getRegleproporAssujettie()) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
				+ devisObject.getRegleproporAssujettie());
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())
				- devisObject.getRegleproporAssujettie());
				  devisObject.setSurplusEncaisse(0F);

				}

		    
		    }else{
		    
		    devisObject.setDepassplafond(devisObject.getDepassplafondInput());
		    
		    devisObject.setTotalPartAssuree(devisObject.getDepassplafondInput()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
				+ devisObject.getRegleproporAssujettie()
		    );


				if((Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInput()
				- devisObject.getRegleproporAssujettie() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getRegleproporAssujettie()
				+ devisObject.getDepassplafondInput()
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getRegleproporAssujettie() 
				- devisObject.getDepassplafondInput()
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    }

	
 }

/******************** END LA CARTE ASSUJETTIE***********************************/



 /********************** AMI ******************/

    if(devisObject.getCompagnieId() == 44 ){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
	       devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(Double.valueOf(devisObject.getTva()));
	     
	 // Engagement GA
	 
	  if(Float.valueOf(devisObject.getTotHt().toString()) < Float.valueOf(devisObject.getCapitalRestant().toString())){
	      
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString()) 
	      - Float.valueOf(devisObject.getVetuste().toString())
	      - Float.valueOf(devisObject.getFranchiseInput().toString()));
	    }else{
	    
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getCapitalRestant().toString()));
	    }
	    
	 // End engagemnt GA
	
		  if(devisObject.getDepassplafondInput() < 0){
		    
		    devisObject.setDepassplafond(0F);
		    devisObject.setTotalPartAssuree(Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );


				if((Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    
		    }else{
		    
		    devisObject.setDepassplafond(devisObject.getDepassplafondInput());
		    
		    devisObject.setTotalPartAssuree(devisObject.getDepassplafondInput()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

        	if((Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInput() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getDepassplafondInput()
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInput() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}

		    }

	
 }

/**************************** ALAMAN TAKEFUL ***********************************/

    if(devisObject.getCompagnieId() == 37){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
	       devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(Double.valueOf(devisObject.getTva()));
	     
	 // Engagement GA
	 
	  if(Float.valueOf(devisObject.getTotHt().toString()) < Float.valueOf(devisObject.getCapitalRestant().toString())){
	      
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotHt().toString()) 
	      - Float.valueOf(devisObject.getVetuste().toString())
	      - Float.valueOf(devisObject.getFranchiseInput().toString()));
	    }else{
	    
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getCapitalRestant().toString()));
	    }
	    
	 // End engagemnt GA
	
		  if(devisObject.getDepassplafondInput() < 0){
		    
		    devisObject.setDepassplafond(0F);
		    devisObject.setTotalPartAssuree(Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

				if((Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    
		    }else{
		    
		    devisObject.setDepassplafond(devisObject.getDepassplafondInput());
		    
		    devisObject.setTotalPartAssuree(devisObject.getDepassplafondInput()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

       if((Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInput() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getDepassplafondInput()
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInput() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}

		    }

	
 }



  end
 
 
 rule "NON Assujettie for  TVA DOMMAGES COLLISIONS" 

 when 
     devisObject: FactDevis(!isAssujettie.equals(true)) && FactDevis(modeId == 5) 
 then
 
 /************************* SALIM ************************/

   if(devisObject.getCompagnieId() == 1 || devisObject.getCompagnieId() == 6 || devisObject.getCompagnieId() == 8 
	 || devisObject.getCompagnieId() == 5|| devisObject.getCompagnieId() == 7 || devisObject.getCompagnieId() == 2
	 || devisObject.getCompagnieId() == 4){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
         devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(0D);
	     
	 // Engagement GA
	 
	  if(Float.valueOf(devisObject.getTotalTtc().toString()) < Float.valueOf(devisObject.getCapitalRestant().toString())){
	      
	     if(devisObject.getDepassplafondInputNonAssujettie() < 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				}
				if(devisObject.getDepassplafondInputNonAssujettie() >= 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				}
	    }
			if(Float.valueOf(devisObject.getTotalTtc().toString()) > Float.valueOf(devisObject.getCapitalRestant().toString())){
	    
	      if(devisObject.getDepassplafondInputNonAssujettie() < 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				}
				if(devisObject.getDepassplafondInputNonAssujettie() >= 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				}
	    }
	    
	 // End engagemnt GA
	
		  if(devisObject.getDepassplafondInputNonAssujettie() < 0){
		    
		    devisObject.setDepassplafond(0F);
		    devisObject.setTotalPartAssuree(
		    Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

				if((Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    
		    }else{
		    
		    devisObject.setDepassplafond(devisObject.getDepassplafondInputNonAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getDepassplafondInputNonAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

        if((Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getDepassplafondInputNonAssujettie()
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}

		    }
	
 }

  /************************* LA CARTE  ************************/
 
   if(devisObject.getCompagnieId() == 3){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
         devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(0D);
	     
	 // Engagement GA
	 
	  if(Float.valueOf(devisObject.getRegleproporNonAssujettieCarte().toString()) < Float.valueOf(devisObject.getCapitalRestant().toString())){

	      if(Float.valueOf(devisObject.getValeurNeufCarte().toString()) < 50000F){

	      devisObject.setEngagementGa(
					(Float.valueOf(devisObject.getTotalTtc().toString()) 
	      -

				 Float.valueOf(devisObject.getVetuste().toString())
				 - Float.valueOf(devisObject.getDroitTimbre().toString())
				 )

				*
                               Float.valueOf(devisObject.getRpDV().toString())
	      -
				 Float.valueOf(devisObject.getFranchiseInput().toString()));

				}
				if(Float.valueOf(devisObject.getValeurNeufCarte().toString()) >= 50000F){

	      if(devisObject.getDepassplafondInputNonAssujettie() < 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				}
				if(devisObject.getDepassplafondInputNonAssujettie() >= 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				}


				}
	    }
			if(Float.valueOf(devisObject.getRegleproporNonAssujettieCarte().toString()) >= Float.valueOf(devisObject.getCapitalRestant().toString()))
			{
	    

	      if(devisObject.getDepassplafondInputNonAssujettie() < 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				}
				if(devisObject.getDepassplafondInputNonAssujettie() >= 0){
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				}

	    }
	    
	 // End engagemnt GA
	devisObject.setReglepropor(devisObject.getRegleproporNonAssujettie());
		  if(devisObject.getDepassplafondInputNonAssujettie() < 0){
		    
		    devisObject.setDepassplafond(0F);
		    devisObject.setTotalPartAssuree(
		    Float.valueOf(devisObject.getFranchiseInput().toString())
				
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
				+ devisObject.getRegleproporNonAssujettie()
		    );

				if((Float.valueOf(devisObject.getTotalTtc().toString())
				
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())
				- devisObject.getRegleproporNonAssujettie()) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString())
				 
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
				+ devisObject.getRegleproporNonAssujettie());
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())
				- devisObject.getRegleproporNonAssujettie());
				  devisObject.setSurplusEncaisse(0F);

				}
		    
		    }else{
		    
		    devisObject.setDepassplafond(devisObject.getDepassplafondInputNonAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getDepassplafondInputNonAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
				+ devisObject.getRegleproporNonAssujettie()
		    );

				if((Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())
				- devisObject.getRegleproporNonAssujettie()) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getDepassplafondInputNonAssujettie()
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
				+ devisObject.getRegleproporNonAssujettie());
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())
				- devisObject.getRegleproporNonAssujettie());
				  devisObject.setSurplusEncaisse(0F);

				}
		    }
	
 }

   /************************* AMI ************************/
 
   if(devisObject.getCompagnieId() == 44 ){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
         devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(0D);
	     
	 // Engagement GA
	 
	  if(Float.valueOf(devisObject.getTotalTtc().toString()) < Float.valueOf(devisObject.getCapitalRestant().toString())){
	      
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString()) 
	      - Float.valueOf(devisObject.getVetuste().toString())
	      - Float.valueOf(devisObject.getFranchiseInput().toString()));
	    }else{
	    
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getCapitalRestant().toString()));
	    }
	    
	 // End engagemnt GA
	
		  if(devisObject.getDepassplafondInputNonAssujettie() < 0){
		    
		    devisObject.setDepassplafond(0F);
		    devisObject.setTotalPartAssuree(
		    Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );


				if((Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    
		    }else{
		    
		    devisObject.setDepassplafond(devisObject.getDepassplafondInputNonAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getDepassplafondInputNonAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

				if((Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getDepassplafondInputNonAssujettie()
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    }
	
 }

  /************************* BIAT ************************/

   if(devisObject.getCompagnieId() == 35){
   
         
devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
         devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(0D);
	     
	 // Engagement GA
	 
	  if(Float.valueOf(devisObject.getTotalTtc().toString()) < Float.valueOf(devisObject.getCapitalRestant().toString())){
	      
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString()) 
	      - Float.valueOf(devisObject.getVetuste().toString())
				- Float.valueOf(devisObject.getDroitTimbre().toString())
	      - Float.valueOf(devisObject.getFranchiseInput().toString()));
	    }else{
	    
	      devisObject.setEngagementGa(
					Float.valueOf(devisObject.getCapitalRestant().toString())
					- Float.valueOf(devisObject.getFranchiseInput().toString()));
	    }
	    
	 // End engagemnt GA
	
		  if(devisObject.getDepassplafondInputNonAssujettie() < 0){
		    
		    devisObject.setDepassplafond(0F);
		    devisObject.setTotalPartAssuree(
		    Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

				if((Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    
		    }else{
		    
		    devisObject.setDepassplafond(devisObject.getDepassplafondInputNonAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getDepassplafondInputNonAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

        if((Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getDepassplafondInputNonAssujettie()
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}

		    }
	
 }

  /************************* ALAAMANA TAKAFUL ************************/

   if(devisObject.getCompagnieId() == 37 ){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
         devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(0D);
	     
	 // Engagement GA
	 
	  if(Float.valueOf(devisObject.getTotalTtc().toString()) < Float.valueOf(devisObject.getCapitalRestant().toString())){
	      
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getTotalTtc().toString()) 
	      - Float.valueOf(devisObject.getVetuste().toString())
	      - Float.valueOf(devisObject.getFranchiseInput().toString()));
	    }else{
	    
	      devisObject.setEngagementGa(Float.valueOf(devisObject.getCapitalRestant().toString()));
	    }
	    
	 // End engagemnt GA
	
		  if(devisObject.getDepassplafondInputNonAssujettie() < 0){
		    
		    devisObject.setDepassplafond(0F);
		    devisObject.setTotalPartAssuree(
		    Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

				if((Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    
		    }else{
		    
		    devisObject.setDepassplafond(devisObject.getDepassplafondInputNonAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getDepassplafondInputNonAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString())
		    );

					if((Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getDepassplafondInputNonAssujettie()
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString())
				- devisObject.getDepassplafondInputNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
		    }
	
 }
 
 
 end
