package com.gaconnecte.auxilium.drools


import com.gaconnecte.auxilium.drools.FactDevis

rule "Assujettie for  TVA VOL" 

 when 
     devisObject: FactDevis(isAssujettie.equals(true)) && FactDevis(modeId == 8) 
 then
 
  
/********************** ALL ******************/

   if(devisObject.getCompagnieId() == 1 || devisObject.getCompagnieId() == 5 || devisObject.getCompagnieId() == 7 
	 || devisObject.getCompagnieId() == 8 || devisObject.getCompagnieId() == 6){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
	       devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(Double.valueOf(devisObject.getTva()));
	     
	 // Engagement GA
	 
	  
			
	    
	      devisObject.setEngagementGa( - Float.valueOf(devisObject.getFranchiseInput().toString()) + (Float.valueOf(devisObject.getTotHt().toString())
	      - Float.valueOf(devisObject.getVetuste().toString()))
				 * devisObject.getRpVI()) ;
	    
	    
	 // End engagemnt GA
	
		  
		    
		    devisObject.setReglepropor(devisObject.getRegleproporAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getRegleproporAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));

					if((Float.valueOf(devisObject.getTotalTtc().toString())
			  -	devisObject.getRegleproporAssujettie() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getRegleproporAssujettie() 
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				-	devisObject.getRegleproporAssujettie()
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
	
 }

    if(devisObject.getCompagnieId() == 2){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
	       devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(Double.valueOf(devisObject.getTva()));
	     
	 // Engagement GA
	 
	  
			
	    
	      devisObject.setEngagementGa( - Float.valueOf(devisObject.getFranchiseInput().toString()) + (Float.valueOf(devisObject.getTotHt().toString())
	      - Float.valueOf(devisObject.getVetuste().toString()))
				 * devisObject.getRpVI()) ;
	    
	    
	 // End engagemnt GA
	
		    devisObject.setReglepropor(devisObject.getRegleproporAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getRegleproporAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getTva().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));

					if((Float.valueOf(devisObject.getTotalTtc().toString())
			  -	devisObject.getRegleproporAssujettie() 
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getRegleproporAssujettie() 
				+ Float.valueOf(devisObject.getTva().toString())
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				-	devisObject.getRegleproporAssujettie()
				- Float.valueOf(devisObject.getTva().toString())
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
	
 }

 

 
 end
 
 
 rule "NON Assujettie for  TVA VOL" 

 when 
     devisObject: FactDevis(!isAssujettie.equals(true)) && FactDevis(modeId == 8) 
 then
 
 

 /************************* ALL ************************/

   if(devisObject.getCompagnieId() == 1 || devisObject.getCompagnieId() == 5 || devisObject.getCompagnieId() == 7
	 || devisObject.getCompagnieId() == 8 ){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
	       devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(0D);
	     
	 // Engagement GA
	 
	  
			
	    
	      devisObject.setEngagementGa( - Float.valueOf(devisObject.getFranchiseInput().toString()) + (Float.valueOf(devisObject.getTotalTtc().toString())
	      - Float.valueOf(devisObject.getVetuste().toString()) - Float.valueOf(devisObject.getDroitTimbre().toString()))
				 * devisObject.getRpVI()) ;
	    
	    
	 // End engagemnt GA
	
		  
		    
		    devisObject.setReglepropor(devisObject.getRegleproporNonAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getRegleproporNonAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));

					if((Float.valueOf(devisObject.getTotalTtc().toString())
			  -	devisObject.getRegleproporNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getRegleproporNonAssujettie() 
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				-	devisObject.getRegleproporNonAssujettie()
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
	
 }

/******************************** ILLOYD ****************************************/

    if(devisObject.getCompagnieId() == 6){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
	       devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(0D);
	     
	 // Engagement GA
	 
	  
			
	    
	      devisObject.setEngagementGa((Float.valueOf(devisObject.getTotalTtc().toString())
	      - Float.valueOf(devisObject.getVetuste().toString()) - Float.valueOf(devisObject.getFranchiseInput().toString()))
				 * devisObject.getRpVI()) ;
	    
	    
	 // End engagemnt GA
	
		  
		    
		    devisObject.setReglepropor(devisObject.getRegleproporNonAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getRegleproporNonAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));

					if((Float.valueOf(devisObject.getTotalTtc().toString())
			  -	devisObject.getRegleproporNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getRegleproporNonAssujettie() 
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				-	devisObject.getRegleproporNonAssujettie()
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
	
 }

 /******************************* GAT **************************************/

     if(devisObject.getCompagnieId() == 2){
   
         
	       devisObject.setVetuste(Float.valueOf(devisObject.getVetuste().toString()));
	       devisObject.setFranchise(Float.valueOf(devisObject.getFranchiseInput().toString()));
		  
	     
	     devisObject.setDroitTimbre(Float.valueOf(devisObject.getDroitTimbre().toString()));
	     devisObject.setTva(0D);
	     
	 // Engagement GA
	 
	  
			
	    
	      devisObject.setEngagementGa((Float.valueOf(devisObject.getTotalTtc().toString())
	      - Float.valueOf(devisObject.getVetuste().toString()) - Float.valueOf(devisObject.getFranchiseInput().toString()))
				 * devisObject.getRpVI()) ;
	    
	    
	 // End engagemnt GA
	
		  
		    
		    devisObject.setReglepropor(devisObject.getRegleproporNonAssujettie());
		    
		    devisObject.setTotalPartAssuree(devisObject.getRegleproporNonAssujettie()
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));

					if((Float.valueOf(devisObject.getTotalTtc().toString())
			  -	devisObject.getRegleproporNonAssujettie() 
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString())) < 0){


					devisObject.setSurplusEncaisse(-Float.valueOf(devisObject.getTotalTtc().toString()) 
				+	devisObject.getRegleproporNonAssujettie() 
				+ Float.valueOf(devisObject.getFranchiseInput().toString())
		    + Float.valueOf(devisObject.getVetuste().toString())
		    + Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSoldeReparateur(0F);
				}else{
         devisObject.setSoldeReparateur(Float.valueOf(devisObject.getTotalTtc().toString()) 
				-	devisObject.getRegleproporNonAssujettie()
				- Float.valueOf(devisObject.getFranchiseInput().toString())
		    - Float.valueOf(devisObject.getVetuste().toString())
		    - Float.valueOf(devisObject.getDroitTimbre().toString()));
				  devisObject.setSurplusEncaisse(0F);

				}
	
 }

 
 
 end
 




   
       


   
       