import { BaseEntity } from '../../../shared';
export class PaiementReparation implements BaseEntity {


    constructor(
        public id?: number,
        public numeroContrat?: string,
        public referenceGa?: string,
        public compagnieId?: number,
        public compagnie?: string,
        public compagnieAdvId?: number,
        public compagnieAdv?: string,
        public agencyNameId?: number,
        public agencyName?: string,
        public zoneId?: string,
        public zone?: string,
        public assureId?: string,
        public assureName?: string,
        public dateDemande?: Date,
        public dateBonDeSortie?: Date,
        public immatriculation?: string,
        public usageId?: number,
        public usageLabel?: string,
         public modeGestionId?: number,
        public modeGestion?: string,
        public posGaId?: number,
        public positionGa?: string,
        public reparateurId?: number,
        public reparateur?: string,
        public reparateurCode?: string,
        public villeId?: number,
        public zoneReparateur?: string,
        public cng?: boolean,
        public cngLabel?: string,
        public expertId?: number,
        public expert?: string,
        public chocBoolean?: boolean,
        public typeChoc?: string,
        public fraisFixe?: string,
        public chargeId?: number,
        public chargeNom?: string,
        public chargePrenom?: string,
        public marqueId?: number,
        public marque?: string,  
        public marqueCode?: string,      
        public creationDate?: Date,    
        public ageVehicule?: string,
        public engagementGA?: number,
        public trancheSinistre?: string,
        public participationAssure?: number,
        public avanceFacture?: number,
        public fraisDossier?: number,
        public factureReparateur?: number,
        public modTtc?: number,
        public pourcentageMod?: number,
        public nature_piece?: string,
        public pdrTtc?: number,
        public ipPf?: number,
        public pourcentagePr?: number,
        public pourcentageIpPf?: number,
        public nbreHeuresReparation?: number,
        public nbreHeuresRemplacement?: number,
        public nbreHeuresPeinture?: number,
        public baseCalculModIp?: number,
        public baseCalculPiece?: number,
        public totalRistourne?: number,
        public total?: number,
        public remboursementReparateur?: number,
        public cngFr?: string,
        public etapePrestation?: string,
        
        public pourcentageIpPfString?: string,
        public datePCirculation?: any,

        public decision?: string,


    ) {
    }

}