import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterModule } from '@angular/router';
import { NgMultiSelectDropDownModule } from 'ng-multiselect-dropdown';
import { DataTablesModule } from 'angular-datatables';
import { AuxiliumSharedModule } from '../../shared';
import {
    SinisterPecService,
    SinisterPecAgentService,
    SinisterPecAgentDialogComponent,
    SinisterPecPopupService,
    SinisterPecComponent,
    SinisterPecDetailComponent,
    SinisterPecDialogComponent,
    SinisterPecPopupComponent,
    SinisterPecDeletePopupComponent,
    SinisterPecDeleteDialogComponent,
    sinisterPecRoute,
    sinisterPecPopupRoute,
    DemandSinisterPecService,
    SinisterPecToApproveComponent,
    DecisionSinisterPecComponent,
    DemandPecInProgressComponent,
    SinisterPecRefused,
    SinisterRepriseDialogComponent,
    SinisterPecCanceled,
    ConsultationDemandePecComponent,
    DemandePecComponent,
    SinisterPecReservesLifted,
    PrestationPECAffectReparationComponent,
    PrestationPECAnnulerAffectReparationComponent,
    SinisterAgentService,
    SinisterPecChangeStatus,
    SinisterPecModificationStatus,
    SinisterPecCanceledAndRefused,
    VerificationOriginalsPrintedComponent,
    ModificationChargeComponent,
    AnnulationPrestationComponent,
    ConfirmationAnnulationPrestationComponent,
    ConfirmationRefusPrestationComponent,
    RefusPrestationComponent,
    CancelExpertMissionaryComponent,
    ExpertMissionaryComponent,
    ImprimeComponent,
    SignatureBonSortieComponent,
    PieceJointeSignatureBonSortieComponent,
    SinisterPecModificationPrestation,
    HistoryPopupDetailsPec,
    AutresPiecesComponent,
    DerogationComponent,
    DerogationPecComponent

} from './';
//import { SinisterAgentService } from './sinister-agent.service';
//import {} from './demand-sinister-pec.service';
import { PriseEnChargeDetailComponent } from './priseencharge-detail.component';
const ENTITY_STATES = [
    ...sinisterPecRoute,
    ...sinisterPecPopupRoute,
];

@NgModule({
    imports: [
        AuxiliumSharedModule,
        DataTablesModule,
        NgMultiSelectDropDownModule,
        RouterModule.forRoot(ENTITY_STATES, { useHash: true })
    ],
    declarations: [
        SinisterPecComponent,
        PrestationPECAnnulerAffectReparationComponent,
        SinisterPecDetailComponent,
        SinisterPecDialogComponent,
        SinisterPecDeleteDialogComponent,
        SinisterPecPopupComponent,
        SinisterPecDeletePopupComponent,
        SinisterPecAgentDialogComponent,
        SinisterPecToApproveComponent,
        DecisionSinisterPecComponent,
        ConsultationDemandePecComponent,
        DemandPecInProgressComponent,
        SinisterPecRefused,
        CancelExpertMissionaryComponent,
        ExpertMissionaryComponent,
        SinisterRepriseDialogComponent,
        SinisterPecCanceled,
        DemandePecComponent,
        SinisterPecReservesLifted,
        PrestationPECAffectReparationComponent,
        SinisterPecChangeStatus,
        SinisterPecModificationStatus,
        SinisterPecCanceledAndRefused,
        VerificationOriginalsPrintedComponent,
        PriseEnChargeDetailComponent,
        ModificationChargeComponent,
        AnnulationPrestationComponent,
        ConfirmationAnnulationPrestationComponent,
        ConfirmationRefusPrestationComponent,
        RefusPrestationComponent,
        ImprimeComponent,
        SignatureBonSortieComponent,
        PieceJointeSignatureBonSortieComponent,
        SinisterPecModificationPrestation,
        HistoryPopupDetailsPec,
        AutresPiecesComponent,
        DerogationComponent,
        DerogationPecComponent
    ],
    entryComponents: [
        SinisterPecComponent,
        SinisterPecDialogComponent,
        SinisterPecPopupComponent,
        SinisterPecDeleteDialogComponent,
        SinisterPecDeletePopupComponent,
        SinisterPecAgentDialogComponent,
        SinisterPecToApproveComponent,
        PrestationPECAnnulerAffectReparationComponent,
        DecisionSinisterPecComponent,
        DemandPecInProgressComponent,
        SinisterPecRefused,
        SinisterRepriseDialogComponent,
        SinisterPecCanceled,
        CancelExpertMissionaryComponent,
        ExpertMissionaryComponent,
        ConsultationDemandePecComponent,
        DemandePecComponent,
        SinisterPecReservesLifted,
        PrestationPECAffectReparationComponent,
        SinisterPecChangeStatus,
        SinisterPecModificationStatus,
        SinisterPecCanceledAndRefused,
        VerificationOriginalsPrintedComponent,
        ModificationChargeComponent,
        AnnulationPrestationComponent,
        ConfirmationAnnulationPrestationComponent,
        ConfirmationRefusPrestationComponent,
        RefusPrestationComponent,
        ImprimeComponent,
        SignatureBonSortieComponent,
        PieceJointeSignatureBonSortieComponent,
        SinisterPecModificationPrestation,
        HistoryPopupDetailsPec,
        AutresPiecesComponent,
        DerogationComponent,
        DerogationPecComponent
    ],
    providers: [
        SinisterPecService,
        SinisterPecPopupService,
        SinisterPecAgentService,
        DemandSinisterPecService,
        SinisterAgentService,
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AuxiliumSinisterPecModule { }
