import { BaseEntity } from '../../shared';

export class PecMonitoringPrestation implements BaseEntity {
    
    constructor(
        public id?: number,
        public referenceGa?: string,
        public referenceCmp?: string,
        public partnerId?: number,
        public partnerName?: string,
        public agencyId?: number,
        public agencyCode?: string,
        public agencyName?: string,
        public insuredName?: string,
        public vehicleId?: number,
        public immatriculation?: string,
        public brandId?: number,
        public brandLabel?: string,
        public marqueCode?: string,
        public modelId?: number,
        public modelLabel?: string,
        public usageId?: number,
        public usageLabel?: string,
        public reparatorRs?: string,
        public reparateurCode?: string,

        public cng?: boolean,
        public expertRs?: string,
        public packName?: string,
        public agencyGovernorateId?: number,
        public agencyGovernorateLabel?: string,
        public incidentDate?: any,
        public sendingDate?: any,
        public managmentModeId?: number,
        public managmentModeLabel?: string,
        public gaPositionId?: number,
        public gaPositionLabel?: string,
        public tiersePartnerId?: number,
        public tiersePartnerName?: string,
        public assignedToId?: number,
        public assignedToName?: string,
        public baremeId?: number,
        public baremeRate?: number,
        public stepId?: number,
        public delaiMoyenDecision?: string,
        public decision?: string,
        public vr?: string,
        public delaiMoyenLeveReserve?: string,
        public typeShock?: string,
        public delaiReparation?: string,
        public vrDays?: number,
        public delaiMoyenDispoAssure?: string,
        public delaiMoyenAffectationRep?: string,  
        public delaiAdministratif?: string,
        public delaiEtablissementDevis?: string,
        public delaiAffectationExpert?: string,
        public delaiAvisExpert?: string,
        public delaiEnvoiEstimation?: string,
        public dateReserves?: string,
        public dateChangeStatut?: string,
        public dateInter?: string,
        public cngFr?: string,
        public stepName?: string,
        public rdvReparateurDate?: any,
        public receiptVehicleDate?: any,
        public datePCirculation?: any,
        public dateAffectExpert?: any,
        public dateAffectReparateur?: any,
        public partAssure?: string,

        public delaiVerificationDevis?: string,
        public dateFacturation?: any,
        public delaiBonSortie?: string,
        public delaiApec?: string,

        public ecartReparation?: string,
        public ecartAcceptationFond?: string,
        public ecartAcceptationForme?: string,



    ) {
    }
}